<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_httpsi.diawi.comZvkaM6</name>
   <tag></tag>
   <elementGuidId>632ffdb3-c006-409f-92ba-0e8d0ccb7879</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='LPlnk798551']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LPlnk798551</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>960c7865-45c2-47d1-9b72-c527924286b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://i.diawi.com/ZvkaM6</value>
      <webElementGuid>bf0bc4db-63f7-4bbe-873e-5c52489df729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>13d31dc8-5594-4e2c-8b2d-3c552b81acd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>280f4d5d-250d-4e1c-94c4-b450a3f0d0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LPlnk798551</value>
      <webElementGuid>0180d1d8-451f-4305-8d42-f6d18d0439e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>previewinformation</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>39dc8a36-4ff6-4580-9da3-767cfc07576a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
https://i.diawi.com/ZvkaM6</value>
      <webElementGuid>bbd4e810-7b69-4da7-8c60-7be1882260ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LPlnk798551&quot;)</value>
      <webElementGuid>9829186c-a3cc-416f-b413-e9d36bb867d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='LPlnk798551']</value>
      <webElementGuid>a7d3e822-605a-4309-9e77-054c066e0311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Item.MessageUniqueBody']/div/div/font/span/a</value>
      <webElementGuid>a49145b7-2033-49ef-b338-360a7ee50d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'https://i.diawi.com/ZvkaM6')]</value>
      <webElementGuid>c7494176-7e2b-400f-8357-ae1bce96226c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide original message'])[2]/following::a[1]</value>
      <webElementGuid>42a6982c-5a7b-4d59-8d2c-244fbb875279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='https://i.diawi.com/XuwH58'])[1]/preceding::a[1]</value>
      <webElementGuid>99c8dbb1-a9d6-46d7-afda-279983431062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reply all'])[4]/preceding::a[2]</value>
      <webElementGuid>e5c8ad6b-92ed-4c90-9906-f908a55e3a47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='https://i.diawi.com/ZvkaM6']/parent::*</value>
      <webElementGuid>70063c37-11d1-45f0-b7cd-47feb967d4ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://i.diawi.com/ZvkaM6')]</value>
      <webElementGuid>618b43a3-4214-4299-82e1-5310c48360f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>6e42691d-f59a-4d67-8caf-5ab5a94bfb7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://i.diawi.com/ZvkaM6' and @id = 'LPlnk798551' and (text() = '
https://i.diawi.com/ZvkaM6' or . = '
https://i.diawi.com/ZvkaM6')]</value>
      <webElementGuid>c3949eeb-bf29-47a1-9c4b-fff5a3e04230</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
