<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Pushpendra Singh  Doctor Consultation d_f7f441</name>
   <tag></tag>
   <elementGuidId>fd3f53ee-6e46-4319-928f-da54a23c93c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='primaryContainer']/div[5]/div/div/div/div[5]/div[3]/div/div[5]/div/div/div/div[3]/div[2]/div[2]/div[6]/div/div[2]/div/div[2]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._rp_g4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f3f47b3c-0131-4d60-9a68-0b379ab73fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_rp_g4</value>
      <webElementGuid>3a517673-93ef-4b9e-8e59-d39647c13253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>                                       Pushpendra Singh  Doctor Consultation development build  Tue 17/05, 19:20  Please find doctor consultation development build (version-6.0) - Android - https://i.diawi.com/ZvkaM6 IOS - https://i.diawi.com/XuwH58     </value>
      <webElementGuid>cd1e7556-c25d-4320-9a9a-858f81ae0985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;primaryContainer&quot;)/div[5]/div[@class=&quot;conductorContent&quot;]/div[@class=&quot;_n_T&quot;]/div[@class=&quot;_n_X&quot;]/div[@class=&quot;_n_X&quot;]/div[3]/div[@class=&quot;_n_X&quot;]/div[@class=&quot;_n_Y&quot;]/div[@class=&quot;allowTextSelection&quot;]/div[@class=&quot;conductorContent&quot;]/div[@class=&quot;_rp_j&quot;]/div[@class=&quot;_rp_j allowTextSelection&quot;]/div[@class=&quot;_rp_k allowTextSelection customScrollBar scrollContainer&quot;]/div[2]/div[6]/div[1]/div[2]/div[1]/div[@class=&quot;_rp_f5&quot;]/div[@class=&quot;_rp_f4&quot;]/div[@class=&quot;_rp_g4&quot;]</value>
      <webElementGuid>af484c09-de35-43c2-bacb-31bb9a4b157c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='primaryContainer']/div[5]/div/div/div/div[5]/div[3]/div/div[5]/div/div/div/div[3]/div[2]/div[2]/div[6]/div/div[2]/div/div[2]/div/div[2]</value>
      <webElementGuid>6705bbeb-bcff-4d59-a422-b6591802168f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hide original message'])[1]/following::div[26]</value>
      <webElementGuid>e476206e-9798-46fc-be87-122c8703f63f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='...'])[1]/following::div[59]</value>
      <webElementGuid>dbb1421a-a2cd-4acc-98ee-f0ca19b8175d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div[2]/div/div[2]</value>
      <webElementGuid>878f6f94-602b-4769-a857-a4af563219a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '                                       Pushpendra Singh  Doctor Consultation development build  Tue 17/05, 19:20  Please find doctor consultation development build (version-6.0) - Android - https://i.diawi.com/ZvkaM6 IOS - https://i.diawi.com/XuwH58     ' or . = '                                       Pushpendra Singh  Doctor Consultation development build  Tue 17/05, 19:20  Please find doctor consultation development build (version-6.0) - Android - https://i.diawi.com/ZvkaM6 IOS - https://i.diawi.com/XuwH58     ')]</value>
      <webElementGuid>580bf1fa-ea4f-4f35-9d93-b276401f5915</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
