<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Refresh</name>
   <tag></tag>
   <elementGuidId>6959a608-1dc7-453b-98d6-45f58720fa45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_ariaId_492']/div/div/div/div/div/button/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>94498aa4-95fb-4ea3-9aca-4e0026e70a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autoid</name>
      <type>Main</type>
      <value>_fce_9</value>
      <webElementGuid>6ca6a662-fad9-4137-b991-323ec3b96250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Refresh</value>
      <webElementGuid>4ab7c4e4-31f3-4dcc-b112-d31fafd5945f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_ariaId_492&quot;)/div[@class=&quot;o365cs-base o365cst o365cs-contextMenu&quot;]/div[@class=&quot;_fce_N _fce_x customScrollBar scrollContainer&quot;]/div[@class=&quot;_fce_y&quot;]/div[1]/div[@class=&quot;_fce_z ms-font-s ms-fwt-sl&quot;]/button[@class=&quot;o365button o365cs-contextMenuItem ms-fcl-b-h ms-fcl-b-f ms-fcl-b o365cs-contextMenuItemHover ms-bgc-nl&quot;]/div[@class=&quot;_fce_G&quot;]/span[2]</value>
      <webElementGuid>94d5db64-bfc2-4940-8b24-4c3da4fb4bdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_ariaId_492']/div/div/div/div/div/button/div/span[2]</value>
      <webElementGuid>f0deba76-0961-4f52-903f-fd3c2a37ebaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::span[2]</value>
      <webElementGuid>dedfb25a-4c58-4cf5-a241-68ae4a13d8ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::span[2]</value>
      <webElementGuid>b7c59a53-6e01-43eb-a66d-8233d9ddb199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Automatic replies'])[1]/preceding::span[2]</value>
      <webElementGuid>d6111625-6096-4870-a661-e233a850d761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Display settings'])[1]/preceding::span[4]</value>
      <webElementGuid>7ece7032-8311-40da-b8f1-6010eadcd4bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Refresh']/parent::*</value>
      <webElementGuid>bc6494c4-1fb3-4a29-b8c1-6ff1fd73e790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/div/div/div/div/button/div/span[2]</value>
      <webElementGuid>07d00071-ef59-403e-8939-52011b5dbc69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Refresh' or . = 'Refresh')]</value>
      <webElementGuid>3ec468b6-3533-4c39-a1cf-6e2b19ce86fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
